'*.{js,jsx,ts,tsx}':
  - 'eslint --fix --cache --cache-location .cache/eslint'
  - 'prettier --write'

'*.{scss,css}':
  - 'npx --no-install stylelint --config stylelint.config.mjs --allow-empty-input --fix'
  - 'prettier --write'

'*.{md,json,mdx}':
  - 'prettier --write'
