'*.{js,jsx,ts,tsx}':
  - 'eslint --fix --cache --quiet'
  - 'prettier --write'

'*.{css,scss,sass,module.scss,module.sass}':
  - 'stylelint --fix --allow-empty-input'
  - 'prettier --write'

'*.{md,json,mdx}':
  - 'prettier --write'
